### ISSUE TITLE
`{"contents": [...], "tag": "Tag"}`

### ISSUE THREAD

**Issue by polkovnikov-ph** [haskell/aeson#1004]
Generic-derived `ToJSON` produces JSON with `"contents"` before `"tag"`.

```haskell
data Foo = Foo String | ...

instance ToJSON Foo

print $ encode $ Foo "bar"
```

produces

```json
{
    "contents": "bar",
    "tag": "Foo"
}
```

(prettied manually)

It's both unexpected and inconvenient.

**Comment by phadej** [comment]
Drom `Data.Aeson` documentation:

```haskell
instance ToJSON Person where
    -- No need to provide a toJSON implementation.

    -- For efficiency, we write a simple toEncoding implementation, as
    -- the default version uses toJSON.
    toEncoding = genericToEncoding defaultOptions
```

`toEncoding` (probably) encodes tag first, `toJSON` goes through `Value`, so the order of fields is non-deterministic.

This (needing to providfe `toEncoding` even in default case) is one motivation for #933
