### ISSUE TITLE
GHC 9.6 compatibility: bump ghc-prim and template-haskell upper bounds one notch

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/aeson#1012]
Unfortunately, there's a bunch of dependencies that aren't ready. This is what I had to do to build it:

```
cabal build --allow-newer="aeson:ghc-prim,aeson:template-haskell,these:base,semialign
:base,semigroupoids:base,generically:base" 
```

UPD: edited as suggested below.

**Comment by ysangkok** [comment]
`uuid-types` and [`assoc`](https://hackage.haskell.org/package/assoc-1.1/revision/0.cabal) can be removed from the above command.

This would solve `these` and `semialign`:
* https://github.com/haskellari/these/pull/181
