### ISSUE TITLE
Docs regression (2.2.0.0): lazy-ByteString `decode` and `decodeEither` now documented as strict

### ISSUE THREAD

**Issue by PiDelport** [haskell/aeson#1052]
It looks like this is what happened:

1. https://github.com/haskell/aeson/pull/996 added new implementations of the lazy-ByteString `decode` and `eitherDecode` functions in  `Data.Aeson.Decoding`, but accidentally copied the doc comments from their strict counterparts. ([diff link](https://github.com/haskell/aeson/pull/996/files#diff-c21e30e004152ffd9a6665b7a0109e7707d533e7a33a0193ff5d36059f40dac7R65-R81))

2. https://github.com/haskell/aeson/pull/1036 replaced the old (2.1.2.1) `decode` and `eitherDecode` functions in `Data.Aeson` with the new ones above.

These are the old (2.1.2.1) definitions and docs, for reference:

- [decode](https://github.com/haskell/aeson/pull/1036/files#diff-bca20ff041d5ed1c35b7ff032f19301064e7ac501a4375f312fede2b4cfd90f1L183-L194)
- [eitherDecode](https://github.com/haskell/aeson/pull/1036/files#diff-bca20ff041d5ed1c35b7ff032f19301064e7ac501a4375f312fede2b4cfd90f1L263-L266)

I'm not sure whether the docs should simply be reverted, or whether the new implementations warrant updated docs. Thoughts?

**Comment by phadej** [comment]
I'll welcome the `s/strict/lazy/` patch if there is such mistake.
