### ISSUE TITLE
CI: timeout of 60min a bit tight (or too many constraint sets)

### ISSUE THREAD

**Issue by andreasabel** [haskell/aeson#1061]
This run got canceled after 60 min: https://github.com/haskell/aeson/actions/runs/6010560497/job/16302233028?pr=1055
L'addition:
-  2 min setup
- 15 min build w/o tests
-  5 min build
-  2 min haddock
- 14 min constraint-set text-2.0
-  8 min constraint-set text-1.2
- 13 min+ constraint-set bytestring-0.11.2.0 (got cancelled)

And the hour is over...

**Comment by phadej** [comment]
Resolved in https://github.com/haskell/aeson/pull/1071
