### ISSUE TITLE
Cannot find install plan for GHC 8

### ISSUE THREAD

**Issue by ivanperez-keera** [haskell/aeson#1077]
I'm hitting an issue due to version conflicts.

Our packages `Yampa` and `dunai` depend on `criterion`. We support GHC 7.6 onwards.

Cabal is having trouble finding an installation plan due to issues with `statistics -> async -> hashable`, and `aeson`, which are dependencies of `criterion`.

This only fails for GHC 8. There's a valid install plan for GHC < 8 and for GHC > 8. See: https://app.travis-ci.com/github/ivanperez-keera/dunai/jobs/611989031, https://app.travis-ci.com/github/ivanperez-keera/dunai/jobs/611989185.

What is preventing this from being installed?

**Comment by Bodigrim** [comment]
Did you try increasing `--max-backjumps` as suggested? Set it to 10000 or more. Currently it does not try `primitive < 0.9`.

Another solution is to replace `criterion` with `tasty-bench`, which radically simplifies dependency tree.

**Comment by ivanperez-keera** [comment]
My bad. You're right. I didn't think it would work (`--reorder-goals` didn't), and I admit I had not tried to increase `--max-backjumps`.

**Comment by phadej** [comment]
FWIW you are using very old `cabal-install`

```
$ export CABALVER=2.4
$ export GHCVER=8.0.2
```

you may have reasons, but e.g. even `cabal-install-3.6.2.0` doesn't have any problems finding an install plan:

```
% cabal --version                                                      
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
[polinukli] /codetmp/dunai 00a5045c7e4beb01879d2d0fde1468f3ff5148e4 % time cabal build -w ghc-8.0.2 --dry all --enable-tests --enable-benchmarks
Resolving dependencies...
Build profile: -w ghc-8.0.2 -O1
In order, the following would be built (use -v for more details):
 - Glob-0.10.2 (lib) (requires build)
 - SDL-0.6.7.0 (lib:SDL) (requires download & build)
...
 - criterion-1.4.0.0 (lib) (requires download & build)
 - dunai-0.11.2 (bench:dunai-bench) (first run)
cabal build -w ghc-8.0.2 --dry all --enable-tests --enable-benchmarks  2,61s user 0,23s system 100% cpu 2,829 total
[polinukli] /codetmp/dunai 00a5045c7e4beb01879d2d0fde1468f3ff5148e4 % 
```

The dependency solver in `cabal-install` has improved in the last five years :)

---

I don't see a good reason to use old `cabal-install`s with old GHCs. Updating `cabal-install` shouldn't be an issue. new `cabal-install`s work with older GHCs. And `cabal-install` can be upgraded in isolation (but e.g. upgrading GHC today means also changing `base` version, and vice versa, so upgrading either is not an isolated upgrade).
