### ISSUE TITLE
The instances for `Maybe` fit awkardly with the new type-directed omitting

### ISSUE THREAD

**Issue by michaelpj** [haskell/aeson#1084]
It seems that there are currently two interpretations for `Maybe`:
1. A field that may be `Null`. This is suggested by the fact that `toJSON Nothing = Null` and `fromJSON Null = Nothing`
2. A field that may be omitted. This is suggested by the behaviour of `omittedField` and `omitField`.

However, these fit awkwardly together in at least one case: if `Null` is a valid value of `a`. Then using `.:!=`, `Null` gets interpreted as `Nothing` (which you are interpreting as "omitted") instead of `Just <value>`. 

To give a concrete example, this comes up in the `lsp` package. The LSP spec does silly things like say "`f` is an optional field whose value is an arbitrary JSON object". We interpret that as `f :: Maybe Value`, and so we want to parse `{ "f" : null }" as `f = Just Null` but instead we get `f = Nothing`, which breaks round-tripping etc.

Today we use `.:!`, which doesn't have this problem. I guess another way of looking at this is that `.:!` and `.:!=` can both be used on a field of type `Maybe a`, but do slightly different things!

e.g.

```
let (r :: Result (Maybe Value)) = parse (withObject "whatever" (\o -> o .:! "result")) (Object ("result" .= Null))
in r

>>> Success (Just Null)

let (r :: Result (Maybe Value)) = parse (withObject "whatever" (\o -> o .:!= "result")) (Object ("result" .= Null))
in r
>> Success Nothing
```

I'm not really sure what to say about this. I guess I want a type that _only_ works for omitting fields and whose `FromJSON` instance always delegates to the instance for the underlying type. But we probably can't change the behaviour of `Maybe`, so perhaps it would have to be a new type...

**Comment by michaelpj** [comment]
It's a shame, because the type-directed omitting would actually really help. We have some instances where a field is a type parameter, and is _sometimes_ omissible depending on whether it's `Maybe T` or not. At the moment this is very awkward, and it's _almost_ very nice with the type-directed omitting. Perhaps I just have to define `Omissible` myself...

**Comment by michaelpj** [comment]
Something like this:
```
newtype Omissible a = Omissible (Maybe a)

pattern Present :: a -> Omissible a
pattern Present a = Omissible (Just a)

pattern Omitted :: Omissible a
pattern Omitted = Omissible Nothing
{-# COMPLETE Present, Omitted #-}

instance J.ToJSON a => J.ToJSON (Omissible a) where
  toJSON (Present a) = toJSON a
  toJSON Omitted = error "can't directly encode an omitted value"

  omitField (Present{}) = False
  omitField Omitted = True

instance J.FromJSON a => J.FromJSON (Omissible a) where
  parseJSON v = Present <$> parseJSON v

  omittedField = Just Omitted
```

Writing this makes the wart obvious: `toJSON` is partial. And it's a nasty footgun: you should _only_ use `Omissible` if it's a field in an object and you're using `.=?` to encode it. Awkward.

**Comment by phadej** [comment]
Please condense your thoughts. Until then my fast and knee-jerky reaction:

I think this is at least a cousin of e.g. https://github.com/haskell/aeson/issues/863.

To put it bluntly, don't put anything that can be encoded to `null` inside `Maybe`. `Maybe` encoding won't change in `aeson`, it's fine when values in `Just` cannot be `null`.

**Comment by michaelpj** [comment]
Yes, I think that's a fair diagnosis, everything should work fine except in that case. So arguably what I was doing was already broken!

Condensed version: would you be interested in me contributing the above `Omissible` type, which doesn't have the Null problem but has some slightly different sharp edges? Given that it does have sharp edges that I can't see how to avoid, I think it would be pretty reasonable to say "no", and I'll just define it locally.

**Comment by phadej** [comment]
It's an option to make `Null` of `Value` be omitted. Then you could use `Value` directly, instead of `Maybe Value`. Please open issue about that. I have to think about that, it doesn't feel to be a bad nor too much breaking idea.

**Comment by michaelpj** [comment]
> The awkwardness and rough edge of Omissible stems from the fact that we don't have separate class(es) for encoding/decoding fields of records.

Yes, I agree that would fit. I guess that would be another approach to type-based omitting. Since we went a different way I won't hold my breath :)

> Then you could use Value directly, instead of Maybe Valu

I don't want to do that. I also have other types for which `null` is a valid value (you don't want to know).

> E.g. the occasional need of treating null value as if the field was omitted is so unelegant too. If you can, make reasonable JSON schemas. I'm sorry I cannot help you with your LSP problems, blame Microsoft.

I am, indeed also doing that. It's ridiculous. So I'm trying to cope with fields that might be missing, might be legitimately null, or might be illegitimately null but generously treated as missing. Don't worry, I very much blame Microsoft :joy:

**Comment by phadej** [comment]
> Since we went a different way I won't hold my breath :)

The current approach broke very little consumers, it was (hopefully) a general improvement. But adding a new classes would be a very breaking change (virtually everyone would need to derive them for their types), and I feel that current Haskell ecosystem atmosphere is "avoid breaking changes at all cost"

**Comment by michaelpj** [comment]
Yes, lacking default superclasses the current approach definitely makes sense and will still make my life better!
