### ISSUE TITLE
[Feature] Support for "JSON with Comments" 

### ISSUE THREAD

**Issue by AresAndy** [haskell/aeson#1093]
Version used: `2.2.1.0`

As of mentioned version, if the provided JSON contains comments, the parser fails.
A bit of a controversial topic, I know. the ECMA standard *does not* allow for Cxx-style comments like `//` and `/* .. */`
yet there are some applications (like Visual Studio Code) who make such perhaps improper usage of the format.
Is there a way to support such idiosyncrasies without having the parser fail, or performing pre-filtering of the input?

**Comment by phadej** [comment]
To be clear: the default behavior of `aeson` won't change. The invalid JSON must be rejected. In fact there are tests in JSONTestSuite, e.g. https://github.com/haskell/aeson/blob/c41604b4f29b850fddc56d666a918062a2c989a2/tests/JSONTestSuite/test_parsing/n_object_trailing_comment_slash_open.json

One can imagine having an optional tokenizer (a variant of https://hackage.haskell.org/package/aeson-2.2.1.0/docs/Data-Aeson-Decoding-ByteString.html), but I think it would be better as a separate package.
