### ISSUE TITLE
Add quickstart example to Readme

### ISSUE THREAD

**Issue by malteneuss** [haskell/aeson#1113]
I find myself looking at https://williamyaoh.com/posts/2019-10-19-a-cheatsheet-to-json-handling.html all the time to lookup how to use Aeson instead of https://hackage.haskell.org/package/aeson/docs/Data-Aeson.html (too hidden, too extensive for most of my look ups).

I would like to add a short quickstart section like https://github.com/yesodweb/persistent and other libraries with one or two examples on how to use aeson 80% of the time and to get a quick glimpse of its ergonomics on page 1.

Would that be worthwhile in your opinion?

**Comment by phadej** [comment]
that blog post is longer than header docs for `Data.Aeson`, i'm confused.

**Comment by phadej** [comment]
And the main problem is that your "80%" of the time usage of `aeson` may be completely disjoint with e.g .my "80% of the time" usage of `aeson`. After all, `aeson` is quite low-level library and some people may prefer using `aeson-deriving`, or `autodocodec` or something else which build on top.

**Comment by malteneuss** [comment]
Sorry for the confusion. What i meant was that from the blogpost i like the first basic examples to understand how to use Aeson standalone. 

More precisely, i would like to add a similar but more concise example that shows how to derive Aeson typeclasses like

```haskell
{-# LANGUAGE DeriveGeneric  #-}
{-# LANGUAGE DeriveAnyClass #-}

import Data.Aeson
import GHC.Generics

data Foo = Foo
  { field1 :: Int
  , field2 :: String
  }
  deriving (Show, Generic, ToJSON, FromJSON)
```

how to encode and decode Values

```haskell
import qualified Data.ByteString.Lazy as LB

jsonString :: LB.ByteString
jsonString = "{ \"field1\": 27, \"field2\": \"hello!\" }"

maybeFoo :: Maybe Foo
maybeFoo = decode jsonString

myFoo :: Foo
myFoo = Foo
  { field1 = 909
  , field2 = "take your time"
  }

λ> encode myFoo
```

and how to build values directly:

```haskell
{-# LANGUAGE OverloadedStrings #-}

customValue :: Value
customValue = object
  [ "list_price" .= (150000 :: Int)
  , "sale_price" .= (143000 :: Int)
  , "description" .= ("2-bedroom townhouse" :: String)
  ]
```

Below the examples there could be links to further more involved examples and other related packages.

**Comment by phadej** [comment]
The

```haskell
data Foo = Foo
  { field1 :: Int
  , field2 :: String
  }
  deriving (Show, Generic, ToJSON, FromJSON)
```

is unfortunately wrong. The `Data.Aeson` first section tells what to do https://hackage.haskell.org/package/aeson-2.2.3.0/docs/Data-Aeson.html#g:1

There's also whole another discussion of https://github.com/haskell/aeson/issues/854 i.e. not using `Generics` deriving at all, it's brittle. So the next section in docs of `Data.Aeson` (how to write instances manually by hand) is important info too.

---

I'm sorry, but I don't feel like there is "quickstart to `aeson`"; especially for people not familiar with `aeson` it can be very bad idea, i.e. quickstart to failure.
