### ISSUE TITLE
aeson can violate properties of the data structures (HashMap, Map) when decoding

### ISSUE THREAD

**Issue by qnikst** [haskell/aeson#1120]
Hello, I've faced following bug in the code where I was not able to find key in a HashMap that I'm reading from json.

Here is a minimal example.

``` haskell
{-# LANGUAGE DeriveAnyClass #-}
import GHC.Generics
import Data.Hashable (Hashable)
import Data.HashMap.Strict (HashMap)
import Data.HashMap.Strict qualified as HashMap
import Data.Aeson
import Data.Text (Text)

newtype Host = Host Text
  deriving stock Generic
  deriving anyclass Hashable
  deriving anyclass FromJSON
  deriving newtype FromJSONKey
  deriving anyclass ToJSON
  deriving newtype ToJSONKey
  deriving stock (Show, Eq, Ord)

foo :: Host
foo = Host "foo"

mx :: Maybe (HashMap Host Int)
mx = decode "{\"foo\": 1}"

test :: Maybe Int
test = mx >>= HashMap.lookup foo
```

When running in ghci, and call `test` I expect to get `Just 1` but instead I get `Nothing`. If I change `deriving anyclass Hashable` to `deriving newtype Hashable` everything works as expected.

In the core of the problem is type `Host` that is `Coercible` to `Text`, but has different Hashable instance, in this case key can't be found in constructed hashmap.

The versions of libraries in the example:
- `aeson-2.2.3.0`
- `hashable-1.4.7.0` (it works with hashable-1.4.3.0 because GND and Generic deriving works the same)
- `unorderd-containers-0.2.20`

**Comment by qnikst** [comment]
After some consideration if this is an issue and discussion with local community I've deided to reopen an issue.

Currently it happens that it's possible to make aeson generate structures (Map and HashMap, depending on the flag that violates internal invariants. This is happening when two  instances are not in correlation, FromJSONKey and Hashable (or Old depending on flags). This is documented in comments in sources, but the user has no chances to see that when he writes instances. Moreover behaviour may change with a minor change of the dependencies (that is what happened with hashable).

I think that this is happening because FromJSONKey behaviour controls two things:
1. if we can store key as text field (when it structural equivalent to Text)
2. if we can coerce internal object structure to the target (if Hashable, or Ord structure is the same).

But in code we check only the former and assume the latter if the former is the case. I think that solution may be to differentiate with those two scenarios. For example have

```
class FromJSONKEy where
   fromKey = ...
   hasMatchingInstances :: Bool -- name should be better
   default hasMatchiningInstances = False
```

In this case generic deriving can generate False, so there will be no unsafeCoerce of structures, but provide a newtype for DerivingVia for fast instances.

Or at least call constructor `UnsafeFromJSONKeyCoerce`

**Comment by phadej** [comment]
The mistake is in 

```
  deriving anyclass Hashable
  deriving newtype FromJSONKey
```

why on Earth, you `newtype` derive `FromJSONKey` (probably because you cannot generaically derive it), but derive `anyclass Hashable`.

The 

> In this case generic deriving can generate False

doesn't hold, you use `newtype` deriving.

---

I'm not opposed to remove whole fast-semi-unsafe-coerce deserialisation in long term (it's a hack, and not that commonly hit to justify unsafety). But as that will be breaking change, I won't do it alone.

**Comment by cblp** [comment]
@phadej If you need more practical example, ~~их есть у нас~~

```haskell
newtype Domain = Domain Text
    deriving newtype (Eq, FromJSONKey, Show)

instance Ord Domain where
    compare = compare `on` \(Domain t) -> reverse $ splitOn "." t

main = do
    let mx :: Map Domain Int =
            either error id $ eitherDecode "{\"foo.bar\": 1, \"baz.quz\": 2}"
    print mx -- fromList [("baz.quz",2),("foo.bar",1)]
    print $ Map.lookup (Domain "foo.bar") mx -- Nothing
```

This version works with default flags.

**Comment by phadej** [comment]
> IMHO, FromJSONKey mustn't assume any specific Ord nor Hashable.

Again, if you write manual `Ord` instance, you must write manual `FromJSONKey` instance. Documentation may be improved on that case, but at worst you get weird behavior. You cannot accidentally make the program segfault. Instances must be coherent. It's no significantly different than having `Ord` and `Eq` agree.

**Comment by qnikst** [comment]
Just to tell that in my case it lead to a severe unnoticed bug in production, I’d really be happy if it segfaulted because in that case problem will be noticed immediately on test stands. And the problem appeared after a minor bump of hashable that was not expected

though I agree on a resolution because  I don’t see a good ways forward that will not break more than they heal.
