### ISSUE TITLE
`listParser` does not record `JSONPath`

### ISSUE THREAD

**Issue by mniip** [haskell/aeson#1122]
The docs call it a "Helper function to use with liftParseJSON", but it differs from the actual default implementation of `parseJSONList`. It produces a different error message upon type mismatch, and doesn't use `<?> Index idx` to record the fact that we've descended into an array element.

**Comment by phadej** [comment]
`parseJSONList` is not `liftParseJSON`

**Comment by mniip** [comment]
But what about
```
> eitherDecode @[Compose (Const Void) Identity ()] "[false]"
Left "Error in $: Cannot parse Void"
```
Shouldn't this say error in `$[0]`? C.f:
```
> eitherDecode @[Const Void (Identity ())] "[false]"
Left "Error in $[0]: Cannot parse Void"
```
