### ISSUE TITLE
Add regression tests for the mapping of types to their json format

### ISSUE THREAD

**Issue by bergmark** [haskell/aeson#365]
We have a lot of roundtrip tests for the formats but they don't verify that the format doesn't accidentally change (as could be seen by the format for Either accidentally changing in v0.10).

Would someone be interested in adding a comprehensive set of tests for all instances? First priority is to check the format on successful encoding/decoding. An extension of this is to also verify that bad input isn't allowed, but that is more open-ended.

See https://github.com/bos/aeson/blob/master/tests/UnitTests.hs#L216

**Comment by bergmark** [comment]
I'm re-opening this since I'm working on making it more comprehensive.

**Comment by phadej** [comment]
I think this in a good shape, if you think otherwise let's re-open *with an explicit list of types*, otherwise this is not actionable.
