### ISSUE TITLE
Generic encoding of data type with single nullary constructor

### ISSUE THREAD

**Issue by linearray** [haskell/aeson#473]
`data Foo = Foo deriving (Show,Generic,ToJSON,FromJSON)`

> > encode Foo
> "[]"

Is this behaviour intentional? When reading through the documentation for defaultOptions I saw nothing that would indicate this sort of "shortcut".

**Comment by hvr** [comment]
FWIW, it's consistent with the encoding for the canonical single-nullary-constructor case `encode ()` :-)

**Comment by phadej** [comment]
hmm, https://github.com/bos/aeson/blob/master/tests/UnitTests/NullaryConstructors.hs show something rather different, or are missing some case?

**Comment by linearray** [comment]
In the test cases C1 is one of three type constructors for the data type Nullary.

To trigger the reported behaviour you need a data type with a single nullary type constructor.

**Comment by bergmark** [comment]
Is this solved by the `allNullaryToStringTag` flag of the deriving options?

**Comment by linearray** [comment]
No. Regardless of its setting, with the default being `True`, the output is the same.

**Comment by bergmark** [comment]
Changing defaults is scary since this isn't caught by the type checker. Too bad the default is what we'd like to change here :(

What are our other options?

1. Adding a new option only targeting single constructors: seems ad hoc
2. Adding a new option is a "fixed" allNullaryToStringTag: confusing in docs and inconsistent if used with allNullaryToStringTag
3. Adding a new option and removing the old one: Breaks code but in a good way, could be backwards compatible
4. Changing the type of the current option to cover all three cases: Also breaks in a good way + backwards compat

I'm leaning towards number 3.

**Comment by linearray** [comment]
`allNullaryToStringTag` is `True` by default, so I do not see Option 3 being much different from changing the default right away (assuming the new option will also be `True` by default).

People with old, generically produced JSON data stored away will only be able to read it back in manually.
People, who rely on the current output (JSON schema, etc.) will be surprised.

**Comment by Lysxia** [comment]
What are the three cases?

Single-constructor types are unwrapped as a list, a new option to disable this unwrapping would actually make for a less ad-hoc behavior, and allow `allNullaryToStringTag` and `sumEncoding` options to apply.

**Comment by bergmark** [comment]
Does #522 resolve this in a good way for you @linearray?

**Comment by linearray** [comment]
I did not have any time to test this, but from a quick glance I think this is the best solution one can hope for. Thanks for implementing!

**Comment by phaazon** [comment]
I’ve come across the same problem, which is not solved.

**Comment by phaazon** [comment]
IMHO, the expected output would be `"Foo"`. Such a type should be nullable `String`. If you add a `| Bar` constructor to `Foo`, you end up with such a `String` representation.

**Comment by Lysxia** [comment]
Since aeson-1.2, this is an option, which still needs to be turned on manually.

```haskell
instance ToJSON Foo where
    toJSON = genericToJSON defaultOptions{tagSingleConstructors=True}
```

```haskell
> toJSON Foo
String "Foo"
```

**Comment by phaazon** [comment]
Oh, thank you very much!

**Comment by masaeedu** [comment]
Can this issue be closed, given that the relevant option has been implemented and appears to satisfy the use case?
