### ISSUE TITLE
Limit incoming JSON to a reasonable size

### ISSUE THREAD

**Issue by DemiMarie** [haskell/aeson#505]
Aeson uses some unsafe code, so we should limit the size of JSON we handle to a reasonable value to avoid integer overflow bugs (at least as long as we don't support streaming).

**Comment by phadej** [comment]
I guess if the input JSON is around 2^32 bytes, there will be other problems than just `Int` overflow. Or am I missing something?

**Comment by bergmark** [comment]
@DemiMarie does the new (opt-in) pure version of Unescape lessen your worries about unsafe code? Is it sufficient to close this?

**Comment by phadej** [comment]
No info. Closing.

**Comment by phadej** [comment]
You say, 

>  some unsafe code, 

What is that code in particular?
