### ISSUE TITLE
UnescapePure is slow (was: and memory hungry)

### ISSUE THREAD

**Issue by ndmitchell** [haskell/aeson#593]
In recent aeson releases my program has started using more memory and taking more time. It seems to coincide with UnescapePure vs UnescapeFFI switch, so I wrote a benchmark. First I modified `aeson` to expose both modules, and then wrote a comparison test harness:

```haskell
{-# OPTIONS_GHC -O2 #-}

import Data.Aeson.Parser.UnescapeFFI as FFI
import Data.Aeson.Parser.UnescapePure as Pure
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as BS
import System.Environment

main = do
    [mode,n] <- getArgs
    let f = case mode of
            "ffi" -> FFI.unescapeText
            "pure" -> Pure.unescapeText
            _ -> error "Unknown mode"
    putStrLn $ either show (show . T.length) $ f $ BS.concat $ replicate (read n) $ BS.pack "\\\""
```

Running `test pure 10000000 +RTS -s` gave:

```
   2,318,823,632 bytes allocated in the heap
   3,241,094,200 bytes copied during GC
     679,727,872 bytes maximum residency (15 sample(s))
     213,781,760 bytes maximum slop
            1713 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0      2141 colls,     0 par    5.641s   6.121s     0.0029s    1.7980s
  Gen  1        15 colls,     0 par    0.031s   0.017s     0.0011s    0.0051s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.734s  (  0.770s elapsed)
  GC      time    5.672s  (  6.138s elapsed)
  EXIT    time    0.016s  (  0.180s elapsed)
  Total   time    6.422s  (  7.088s elapsed)

  %GC     time      88.3%  (86.6% elapsed)

  Alloc rate    3,157,547,073 bytes per MUT second

  Productivity  11.7% of total user, 13.4% of total elapsed
```

Running `test ffi 10000000 +RTS -s` gave:

```
     540,061,448 bytes allocated in the heap
     495,318,408 bytes copied during GC
     130,575,192 bytes maximum residency (8 sample(s))
       2,094,248 bytes maximum slop
             297 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       454 colls,     0 par    0.328s   0.396s     0.0009s    0.1139s
  Gen  1         8 colls,     0 par    0.000s   0.003s     0.0004s    0.0008s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.172s  (  0.200s elapsed)
  GC      time    0.328s  (  0.399s elapsed)
  EXIT    time    0.000s  (  0.044s elapsed)
  Total   time    0.500s  (  0.643s elapsed)

  %GC     time      65.6%  (62.0% elapsed)

  Alloc rate    3,142,175,697 bytes per MUT second

  Productivity  34.4% of total user, 37.9% of total elapsed
```

So the FFI is over 12x faster, and has a peak memory over 5x less when unpacking a 10Mb highly-escaped payload (not actually all that unusual). It seems particularly interesting that @bos's last [blog post](http://www.serpentine.com/blog/2015/05/13/sometimes-the-old-ways-are-the-best/) was about exactly these issues.

I note that the FFI code is disabled by default because of "security". I also note the C code is quite a bit simpler and the Haskell code does unchecked bounds access - was there some other security concern that made you pick the Haskell by default?

CC @eskimor @jprider63

**Comment by eskimor** [comment]
Yeah the Haskell version does unchecked bounds stuff, that's why I took the time to prove it correct. I have not done this for the C version. If the C version is that much faster, there is definitely something that needs to be done. Either improve the Haskell version or switch back. But I really would not take "security" lightly, even if the version is correct now, it might no longer be with the next contribution.

12x slower is serious though, I guess I have to prove the C version to be correct too.

**Comment by eskimor** [comment]
Thank you for the benchmark!

**Comment by eskimor** [comment]
The concern was that the C version does a lot of unsafe stuff (well it is C) and was hard to understand for me. So I suggested to switch to the Haskell version, but I realized it uses unsafe stuff too. But in comparison to C the unsafe usages are easy to localize (grep for unsafe) and I proved them to respect array bounds. I simply haven't done this for the C version yet.

**Comment by eskimor** [comment]
Deleted my previous comment, the C version is actually pretty short - should not be too hard to prove it correct.

**Comment by ndmitchell** [comment]
Taking the time to prove something correct is very valuable, and does increase the security confidence. Can you write some notes on how you proved it correct in the file? Is it automatic? A manual argument? Are there artifacts to rerun the proof?

**Comment by eskimor** [comment]
It was a manual argument, to cite the issue from back then:

I am currently checking the Haskell version for out of bounds problems, it is unsafe but looks ok. pos gets advanced at most by 1 during a fold over the input and the output is set to the same length. So it should not overflow. Except that the above is not true in one case:

https://github.com/bos/aeson/blob/master/pure/Data/Aeson/Parser/UnescapePure.hs#L164

it should be fine though, because:

1. To reach this line we need the UTF state to be UtfGround with w larger than 0xffff
2. UtfGround can be reached from f directly but only with a single byte (max 0xff), other than that it has to come from decode.
3. decode can produce UtfGround in two cases
   -> in the first case it also uses a single byte as source for w - so we are fine
   -> in the second case utf state had to be UtfTail1 previously, UtfTail1 only gets produced by decode, and it is handled with the last case branch in runUtf which does not advance pos.
4. Therefore it is guaranteed that the pos only gets incremented twice, if it wasn't incremented in the previous step. 

Referenced issue, [here](https://github.com/bos/aeson/issues/538). But I have to admit that the C code, now that i look at it again, is really pretty short and only has one loop - it should not be hard to see whether this implementation is correct or not.

**Comment by eskimor** [comment]
This is the correct line: https://github.com/bos/aeson/blob/66080da43ec62aa878f6abf039b5a86ba22d6d74/pure/Data/Aeson/Parser/UnescapePure.hs#L171

**Comment by ndmitchell** [comment]
Can I suggest adding that argument to the code?

**Comment by eskimor** [comment]
Definitely ;-) I will file a PR in the course of this week, I will also try a proof of the C version.

**Comment by jprider63** [comment]
My intention was to optimize the Haskell code to perform as closely to the C code as possible, but I haven't gotten around to it. @jaspervdj recently gave me some advice on how to optimize this, so I'll take a shot at this soon. 

Once we have a fast implementation, I plan to prove there are no out of bounds errors using Liquid Haskell. This would be an automatic proof that could be added to the Travis tests.

**Comment by ndmitchell** [comment]
Make sure that you're not just benchmarking time - the memory usage was actually the big problem for me. I had to recompile my Stackage snapshot with `cffi`, which was a real pain (a release defaulting to `cffi` would be great in the meantime until the Haskell matches it).

**Comment by phadej** [comment]
@ndmitchell I think that in this case time and memory usage are correlated (see productivity), and the pure code slowdown is caused by excess allocations.

**Comment by jprider63** [comment]
FYI, these are the baseline numbers for my machine (LTS 6). 

FFI:
```
   1,180,069,432 bytes allocated in the heap
     564,828,032 bytes copied during GC
     161,374,464 bytes maximum residency (10 sample(s))
       5,647,560 bytes maximum slop
             319 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0      2133 colls,     0 par    0.182s   0.186s     0.0001s    0.0003s
  Gen  1        10 colls,     0 par    0.263s   0.361s     0.0361s    0.1660s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.250s  (  0.235s elapsed)
  GC      time    0.445s  (  0.547s elapsed)
  EXIT    time    0.002s  (  0.020s elapsed)
  Total   time    0.699s  (  0.802s elapsed)

  %GC     time      63.7%  (68.1% elapsed)

  Alloc rate    4,712,022,264 bytes per MUT second

  Productivity  36.3% of total user, 31.6% of total elapsed
```

Pure:
```
  14,792,598,888 bytes allocated in the heap
   8,416,261,320 bytes copied during GC
   1,889,245,000 bytes maximum residency (16 sample(s))
      37,406,904 bytes maximum slop
            3660 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     28228 colls,     0 par    3.156s   3.215s     0.0001s    0.0012s
  Gen  1        16 colls,     0 par    7.557s   8.692s     0.5433s    4.4280s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    3.962s  (  3.749s elapsed)
  GC      time   10.713s  ( 11.907s elapsed)
  EXIT    time    0.013s  (  0.270s elapsed)
  Total   time   14.689s  ( 15.926s elapsed)

  %GC     time      72.9%  (74.8% elapsed)

  Alloc rate    3,733,668,106 bytes per MUT second

  Productivity  27.1% of total user, 25.0% of total elapsed
```

bos's commit (05c9e0cbbebc861303fc7dd6b3dfd03844490621):
```
  57,890,071,632 bytes allocated in the heap
     609,018,416 bytes copied during GC
     150,323,568 bytes maximum residency (10 sample(s))
       6,191,944 bytes maximum slop
             297 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     112036 colls,     0 par    0.430s   0.487s     0.0000s    0.0003s
  Gen  1        10 colls,     0 par    0.241s   0.332s     0.0332s    0.1575s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time   15.395s  ( 15.509s elapsed)
  GC      time    0.671s  (  0.819s elapsed)
  EXIT    time    0.002s  (  0.020s elapsed)
  Total   time   16.070s  ( 16.348s elapsed)

  %GC     time       4.2%  (5.0% elapsed)

  Alloc rate    3,760,431,978 bytes per MUT second

  Productivity  95.8% of total user, 94.2% of total elapsed
```

**Comment by jprider63** [comment]
I fixed a memory issue in my [fork](https://github.com/jprider63/aeson) (590fa216c103556f275d9fe5f9ab6050291a9cbd). Previously, I was building an unevaluated monad, but I switched it to use a loop to iterate over the source ByteString. Performance is better than before, but we're not C fast yet. 

```
$ ./slashbench pure 10000000 +RTS -s
10000000
  14,060,102,848 bytes allocated in the heap
     563,743,224 bytes copied during GC
     158,606,872 bytes maximum residency (10 sample(s))
       5,647,744 bytes maximum slop
             313 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     26798 colls,     0 par    0.232s   0.248s     0.0000s    0.0002s
  Gen  1        10 colls,     0 par    0.265s   0.366s     0.0366s    0.1789s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    4.724s  (  4.748s elapsed)
  GC      time    0.498s  (  0.614s elapsed)
  EXIT    time    0.002s  (  0.019s elapsed)
  Total   time    5.225s  (  5.381s elapsed)

  %GC     time       9.5%  (11.4% elapsed)

  Alloc rate    2,976,003,102 bytes per MUT second

  Productivity  90.5% of total user, 87.8% of total elapsed
```

I plan to keep improving this, but I probably won't get back to it for a bit. @ndmitchell, is this change sufficient for now? If so, I can make a pull request.

**Comment by ndmitchell** [comment]
So you're now equal on memory, but 10x slower? Just the memory fixes alone would be useful, since they were causing difficulties on their own - so please do PR.

**Comment by bergmark** [comment]
Thanks for reprting and looking into this!

Regarding running the benchmarks, it may be better to run them using the latest GHC/stackage nightly. I can't say whether it matters for this case, but personally I care more about performance for the latest GHC.

**Comment by ndmitchell** [comment]
For info, all my benchmarks were GHC 8.2.1 using the latest of all libraries as of a week or two ago.

**Comment by jprider63** [comment]
I was benchmarking with LTS 6 since I wanted to compare against the original implementation. I'll use LTS 9 from now on. 

I just created the pull request (#595). These are the number I get. 

```
$ ./slashbench pure 10000000 +RTS -s
10000000
  12,460,095,864 bytes allocated in the heap
     562,242,128 bytes copied during GC
     158,607,976 bytes maximum residency (10 sample(s))
       5,648,240 bytes maximum slop
             313 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     23735 colls,     0 par    0.204s   0.218s     0.0000s    0.0011s
  Gen  1        10 colls,     0 par    0.240s   0.344s     0.0344s    0.1514s

  INIT    time    0.000s  (  0.002s elapsed)
  MUT     time    4.301s  (  4.306s elapsed)
  GC      time    0.444s  (  0.562s elapsed)
  EXIT    time    0.002s  (  0.025s elapsed)
  Total   time    4.749s  (  4.896s elapsed)

  %GC     time       9.4%  (11.5% elapsed)

  Alloc rate    2,896,950,916 bytes per MUT second

  Productivity  90.6% of total user, 88.5% of total elapsed
```

I'll be pretty busy the next few weeks, but I'll try to find some time to try improve this further.

**Comment by eskimor** [comment]
Ok, proving the C version is a bit involved: Lot's of gotos and pointer increments and I also have to check [unescapeText'](https://github.com/bos/aeson/blob/master/ffi/Data/Aeson/Parser/UnescapeFFI.hs#L31) too, for finding out whether the pointers and offsets that are given to [_js_decode_string'](https://github.com/bos/aeson/blob/master/cbits/unescape_string.c#L54) are correct.

Unfortunately, to do this properly I will need a fair amount of time, maybe I get to it at the hackathon next week!
