### ISSUE TITLE
Feature request: a function to run Parser without pass-through

### ISSUE THREAD

**Issue by fumieval** [haskell/aeson#685]
I frequently end up writing `flip J.parseEither () $ const $ do ...`. The following function would be very useful:

```haskell
execParser :: Parser a -> Either String a
execParser m = runParser m [] onError Right
  where onError path msg = Left (formatError path msg)
```

**Comment by phadej** [comment]
@fumieval have you noticed http://hackage.haskell.org/package/aeson-1.4.2.0/docs/Data-Aeson-Types.html#v:parseEither

```haskell
parseEither :: (a -> Parser b) -> a -> Either String b
```

your `execParser = parseEither id`
