### ISSUE TITLE
Decode null to ()

### ISSUE THREAD

**Issue by domenkozar** [haskell/aeson#744]
Sometimes you always expect `null` in a certain field and it would be great if that could get decoded to `()`.

**Comment by phadej** [comment]
See discussion in https://github.com/bos/aeson/issues/542

**Comment by domenkozar** [comment]
Would it be then acceptable to add another unit type to aeson? Currently I have to use `Maybe ()` which is confusing.

**Comment by phadej** [comment]
`Proxy ()`

**Comment by phadej** [comment]
Since this issue had been opened we changed `()` instance so it accepts everything.

To clarify, @domenkozar do you want to check that the field is *exactly* `null`. Have you tried `Proxy anything`, or would you prefer having `data Null = Null` in `aeson`?

**Comment by domenkozar** [comment]
Both work for my use case.
