### ISSUE TITLE
Instance for `()` is unnecessarily strict

### ISSUE THREAD

**Issue by TomMD** [haskell/aeson#788]
```
Prelude Data.Aeson> encode ()
"[]"
Prelude Data.Aeson> decode "[]"
Just ()
Prelude Data.Aeson> decode "{}"
Nothing
```

Could we make `decode "{}" == Just ()`?  Are there strong objections to such a change?  Happy to make a PR.

**Comment by TomMD** [comment]
And as an aside: What the heck happened? Why is this repository multiple megabytes now?

**Comment by phadej** [comment]
There is also #744 and #542.

It's somewhat clear that we won't change `()` encoding to an empty array.

However, IMHO if we will relax decoding, we should relax it to accept *everything*, as anything in between is an arbitrary choice.

**Comment by TomMD** [comment]
> It's somewhat clear that we won't change () encoding to an empty array.

This PR isn't about encoding, is there are reason for the comment other than context?  Also, encoding of `()` is an empty array ( `[ ]` ) so perhaps there is a miscommunication or simple mis-statement.

>  if we will relax decoding, we should relax it to accept everything, as anything in between everything and only [] is an arbitrary choice.

It isn't unreasonable to make `()` succeed for any valid JSON but there is more rational than "arbitrary" here.  It seems framework users that have an awkward time accepting `[]` or `{}` from external sources can easily change the return type to `Aeson.Value` if the API is valid for any JSON.  A custom unit type would be nice but runs into issues with Wall/Werror and discarding the result in do-notation.

The proposed relaxing the decoding has pragmatic roots -  while working with teams using other languages it became clear that `{}` was reasonably assumed to be an acceptable encoding.

More than that, the value `()` indicates a lack of information other than the existence of a non-bottom value. A populated array or dictionary with key-value pairs still seems reasonable to reject as there is more than zero information being provided and this can indicate a misunderstanding or mis-use.  The container-based types also have a mathematically meaningful notion of zero/empty (just ask Monoid) that other types such as Number lacks.

**Comment by phadej** [comment]
> More than that, the value () indicates a lack of information other than the existence of a non-bottom value.

Remember that it was argued that the value `()` should encode / decode to is `null`.

> A populated array or dictionary with key-value pairs still seems reasonable to reject as there is more than zero information being provided and this can indicate a misunderstanding or mis-use

Yet, we silently reject extra keys (until recently added #749).

That said, 'm personally fine with about any change to `()` instances as I avoid using them. It's breaking change, so let's do this and settle on `()` issues for next 3-5 years at least.

@bergmark if you are ok with this, let us also change `-Infinity` `Infinity` and `Nan` encoding/decoding of `Double` and `Float`. https://github.com/bos/aeson/issues/679#issuecomment-436421643 - Let me think what can be done with negative zero.

**Comment by bergmark** [comment]
>  It's breaking change
@phadej are you referring to encoding () to null, or the changes introduced here? I assume the former.

This change sounds good to me, we have precedent for being lenient when parsing. As a side note i'd like to have a module of types that map more naturally to JSON, so you can use e.g. `Null` instead of `Proxy ()` when you care more about the JSON representation than the haskell one.

As for the repo size, I think most of it is because of the JSON test suite that was imported a few years ago.

**Comment by bergmark** [comment]
> @bergmark if you are ok with this, let us also change -Infinity Infinity and Nan encoding/decoding of Double and Float. #679 (comment) - Let me think what can be done with negative zero.

sounds good as well!

**Comment by phadej** [comment]
@bergmark changing the decoder to be more lenient is IMHO also breaking change. E.g. say we start accepting more formats for `UTCTime` - that would change interfaces. The `()` is probably less used, but I'd rather not special-case here.

Bundling `Double` changes resolves the problem whether it's a breaking change or not :) as it forces major change.

Yet, I'd wait until e.g. stackage nightly gets `aeson-1.5` before even thinking about more breaking changes.
