### ISSUE TITLE
IsList instance for Value?

### ISSUE THREAD

**Issue by Gabriel439** [haskell/aeson#813]
If there were an `IsList` instance for `Value` (were `Item Value = Value`) then I believe it would be more ergonomic to create `Value`s directly.  For example, combined with the `IsString` instance for `Value` then an expression like the following would be a valid `Value`:

```haskell
[ "ABC", "DEF" ]
```

I could open a pull request to add the instance if people think this is okay to do

**Comment by phadej** [comment]
How would you implement `toList`? `IsList` is meant (as I interpret it) for kind-a-isomorphic to list structures. `Vector`, `Sequence`. `Map` with `(k,v)` pair as an element.

```haskell
{-# OPTIONS_GHC -Wall #-}

{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE OverloadedLists #-}
{-# LANGUAGE OverloadedStrings #-}

import GHC.Exts (IsList (..))
import Data.Aeson

instance IsList Value where
    type Item Value = Value

    fromList = Array . fromList

    toList (Array xs) = toList xs
    toList _          = []


foo :: Value -> Int
foo [_,_,_] = 3
foo []      = 0
foo _       = -1

-- | >>> foo_ex
-- 0
--
-- /Not/ @-1@
--
foo_ex :: Int
foo_ex = foo "bar"
```

The construction side is fine `fromList`, but `toList` is not suitable for `Value`, in my opinion.

**Comment by Lysxia** [comment]
That's a very good reason to ignore toList and eventually take it out of 
this class. It is quite an artificial obstacle. Does the OverloadedLists 
extension depend on it in any way?

**Comment by phadej** [comment]
@Lysxia yes. List-like pattern matching is made using `toList`.

**Comment by Lysxia** [comment]
One idea is to use `RebindableSyntax`, defining

```
fromList :: ToJSON a => [a] -> Value
fromList = toJSON
```

but the ergonomics are certainly different. Like, since it's just two lines, one might expect users to add them where they want, so there's nothing to do on aeson's side (except maybe document that usage pattern).

**Comment by Gabriel439** [comment]
Oh yeah, I had forgotten about `toList`.  In that case, I'm not as sure about this idea myself, any longer.  Feel free to close
