### ISSUE TITLE
Future of aeson

### ISSUE THREAD

**Issue by bergmark** [haskell/aeson#818]
Hey everyone,

With the move of this repo to the haskell org we can finally add more maintainers! I don't have enough time to spare, so I hope that we can end up with something where I'm not blocking development.

@phadej, @Lysxia, @RyanGlScott, @andrewthad: You have all made great contributions! Would any of you be interested in being added as maintainers? I can't ask anyone to commit to spend time on the project, of course, but the more the merrier as far as I'm concerned!

One remaining practical thing is that I'm not an admin of this repo, anyone know who I can talk to about that?

**Comment by phadej** [comment]
Count me in.

**Comment by andrewthad** [comment]
I appreciate the kind offer, but I must decline. At this time, I have neither the time nor the motivation to help review issues or PRs.

Both @chessai and @emilypi have Owner role on the `haskell` org. I think that either of them should be able to bump your permissions on the `aeson` repo to Admin.

**Comment by Lysxia** [comment]
Sure! You can add me as maintainer.

**Comment by emilypi** [comment]
I'll add anyone that confirms - just ping me!

**Comment by emilypi** [comment]
@bergmark I've added you as admin of this project. Feel free to add new maintainers at will!

**Comment by bergmark** [comment]
Thanks everyone,

@phadej @Lysxia you should have an invite to the repo now and are added on hackage as well.

**Comment by phadej** [comment]
@bergmark thanks for all the work you have done!

**Comment by phadej** [comment]
@bergmark could you add us to the maintainers of `attoparsec-iso8601` too: https://hackage.haskell.org/package/attoparsec-iso8601/maintainers/

**Comment by bergmark** [comment]
done!

**Comment by phadej** [comment]
@bergmark thanks again.
