### ISSUE TITLE
Wrong link in the module regarding `Data.Aeson.QQ`

### ISSUE THREAD

**Issue by KommuSoft** [haskell/aeson#825]
The [documentation of the `Data.Aeson.QQ.Simple` module](http://hackage.haskell.org/package/aeson-1.5.5.1/docs/Data-Aeson-QQ-Simple.html) says:

> Like [Data.Aeson.QQ](http://hackage.haskell.org/package/aeson-1.5.5.1/docs/Data-Aeson-QQ.html) but without interpolation.

There is no `Data.Aeson.QQ` module in the `aeson` package however, but there is such module in the [**`aeson-qq`**](https://hackage.haskell.org/package/aeson-qq) package. I think it might be better if we update the documentation to refer to the correct package.

**Comment by phadej** [comment]
Fixed in https://github.com/haskell/aeson/pull/826
