### ISSUE TITLE
hashable 1.3.1.0 changes aesons property ordering(?)

### ISSUE THREAD

**Issue by bergmark** [haskell/aeson#837]
At least I think this is the case, as a result of https://github.com/haskell-unordered-containers/hashable/pull/196 so sorry if this turns out to be incorrect. Thought i'd file this now in case we want to do something about it quickly before a lot of downstream libs have been updated.

aeson doesn't guarantee ordering of fields, which makes sense. But it is unfortunate if this change to hashable breaks test suites, esp. if it's because of a dependency version changing. Many people are matching aeson output against strings. It could affect "actual" code as well I suppose.

I'm not sure what the best way forward is

1. restrict aeson to an older version of hashable until we make a major release
2. make the latest hashable release unbuildable and publish a major version for it instead.
3. do nothing.

We should probably recommend use of Data.Aeson.QQ(.Simple) in test suites either way. It would have prevented the noise.

@juhp do you have examples of packages with test failures?

**Comment by phadej** [comment]
3. do nothing. I have fixed testsuites, e.f aesons and swagger2 because on different architectures (32/64) the `hashable` is different. There is `aeson-pretty` for example.

Comparing printed `unordered-containers:HashMap` for equality is risky, and I won't consider making `hashable` major bumps when the hash implementation is tweaked in minor ways.

**Comment by bergmark** [comment]
Ok thanks for the quick reply! I'm fine with that.

I wasn't aware that aeson-pretty had confCompare, nice :-)

**Comment by phadej** [comment]
FWIW, for the next `aeson` we can (and probably should to avoid making people sad) make `Show` instance for `Value` stable.
It can be slow and sort keys. I'll do that, soon-ish.

**Comment by bergmark** [comment]
good idea!

so to summarize for anyone else seeing this, workarounds:
* wait for an aeson release with a stable Show
* use aeson-pretty
* compare Values directly or by using Data.Aeson.QQ.Simple (in aeson) or Data.Aeson.QQ (in aeson-qq) - which does not protect against regressions in aeson.

**Comment by phadej** [comment]
Fixed in https://hackage.haskell.org/package/aeson-1.5.6.0
