### ISSUE TITLE
Bug with fieldLabelModifier and rejectUnknownFields

### ISSUE THREAD

**Issue by adrianotm** [haskell/aeson#845]
Hi!

I don't know if this is a bug because i'm quite new to Aeson and Haskell in general.
For example, I have: 
```
data Foo = Foo { _bar :: Int, _baz :: Int }
$(deriveJSON defaultOptions{rejectUnknownFields = True, fieldLabelModifier = drop 1} ''Foo)
```
Then, if I try parsing: `{ "bar": 1, "baz": 1 }`, I get `Error in $: Unknown fields: [\"baz\",\"bar\"]`.

Also, if I try parsing: `{ "_bar": 1, "_baz": 1 }` (which shouldn't work). I get that the key "bar" is not present.

If I understand correctly, the first case should work, because `fieldLabelModifier` takes care of the underscores in the record fields, and when the underscores are gone, then "bar" and "foo" are not unknown fields.
Maybe `fieldLabelModifier` is processed after the `rejectUnknownFields` check? I don't know, maybe I'm missing something.

Thanks!

**Comment by bergmark** [comment]
Which version of aeson are you using? I was not able to reproduce this:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TemplateHaskell #-}
module Main where

import Data.Aeson
import Data.Aeson.TH

data Foo = Foo { _bar :: Int, _baz :: Int }
  deriving Show
$(deriveJSON defaultOptions{rejectUnknownFields = True, fieldLabelModifier = drop 1} ''Foo)

main :: IO ()
main = print $ eitherDecode @ Foo "{ \"bar\": 1, \"baz\": 1 }"
```
=>
```
Right (Foo {_bar = 1, _baz = 1})
```

**Comment by adrianotm** [comment]
Yeah, you are right, I was using 1.4.7.1, which is a year old. Thanks a lot.
