### ISSUE TITLE
Feature request: convenient type for converting seconds since epoch to UTCTime

### ISSUE THREAD

**Issue by Javran** [haskell/aeson#847]
I'm wondering if this project is open to the idea of having more convenient types like `DotNetTime`: as in some cases the time is simply encoded as a floating number (e.g. [`expirationDate` in EditThisCookie extension](http://www.editthiscookie.com/blog/2014/03/cookie-properties/)) describing seconds since epoch, however there isn't a convenient route from `Scientific` to `UTCTime` (please let me know if there's already something exist to do that), so I have to go through `Scientific`, `NominalDiffTime`, and define an `epoch :: UTCTime` and finally get the desired value through `addUTCTime epoch`.

Say `newtype SecondSinceEpoch` or even `newtype SinceEpoch (t :: TimeUnit)` where `data TimeUnit = Second | Millisecond` or so.

**Comment by phadej** [comment]
There is https://hackage.haskell.org/package/time-1.11.1.1/docs/Data-Time-Clock-POSIX.html to work with POSIX time / UNIX epochtime

`NominalDiffTime` has instances.

**Comment by bergmark** [comment]
I've been wanting to do something like this!

I think it would make sense to create a new library for it, so it can iterate independently from aeson. 

Most instances in aeson are "optimized" for cases where you know Haskell is running in the background so e.g. error reporting often mentions names of haskell types.

```
instance FromJSON NominalDiffTime where
    parseJSON = withBoundedScientific "NominalDiffTime" $ pure . realToFrac
```

It would make more sense for a non-haskell consumer to get an error message saying something like "invalid epoch seconds". Perhaps it even makes more sense for haskell conumers, I would have to look up if `NominalDiffTime` accepts seconds or ms or something else.

**Comment by phadej** [comment]
FWIW, yes, we can have a specialized `newtype` (and put it in the same module with `DotNetTime`, `Generallly` from #724, and possibly others similar types - the barrier for inclusion can be relatively low)

**Comment by Javran** [comment]
> There is https://hackage.haskell.org/package/time-1.11.1.1/docs/Data-Time-Clock-POSIX.html to work with POSIX time / UNIX epochtime
> 
> `NominalDiffTime` has instances.

Thanks! No wonder I have some vague memory of doing something similar but way simpler - I forgot about ` Data.Time.Clock.POSIX`.

I'll leave this issue open for more discussion though, as I still need to create an instance to call `posixSecondsToUTCTime`:

```haskell
newtype SecondSinceEpoch = SecondSinceEpoch UTCTime
  deriving (Show) via UTCTime

instance FromJSON SecondSinceEpoch where
  parseJSON =
    fmap (SecondSinceEpoch . posixSecondsToUTCTime)
      . parseJSON @POSIXTime
```

that I wish there are something out of the box - but I don't have a strong opinion on whether it should be in aeson or another individual package.

**Comment by phadej** [comment]
there weren't any further discussion. I close this as resolved.
