### ISSUE TITLE
Add QuickCheck instances for Value

### ISSUE THREAD

**Issue by phadej** [haskell/aeson#915]
Indirectly requested in https://github.com/haskellari/qc-instances/pull/77

I'm :+1:

As I explain in that pull request, adding `aeson` as dependency to `quickcheck-instances` will make `aeson` own testing
less convenient.

@bergmark, @Lysxia do you have an opinion?

**Comment by Lysxia** [comment]
No objections from me.

**Comment by phadej** [comment]
done in 2.0.3.0
