### ISSUE TITLE
Provide explicit failure function

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell/aeson#924]
Currently, `fail` is the only method to fail with an error message. However, I would like to forbid `fail` in my project since it has unexpected behavior in some monads (e.g. in the list monad it returns `[]` instead of throwing an error). So it would be nice if aeson could provide a helper for which `fail` is an alias:
```hs
instance MonadFail Parser where
  fail = parseFail

parseFail :: String -> Parser a
parseFail msg = Parser $ \path kf _ks -> kf (reverse path) msg
```

**Comment by phadej** [comment]
I'm not against adding such function, but I'm confused by your motivation

> e.g. in the list monad it returns [] instead of throwing an error)

Why would it throw? That makes little sense to me, especially as a list monad is a way to model non-deterministic computation, where failure is "not producing any result", i.e. `[]`. In fact, in recent GHCs `fail` should never `error`, that's was the whole idea of MonadFail proposal, which IMHO made using `fail` a lot less error-prone (pun intended).

**Comment by brandon-leapyear** [comment]
Well for one, the IO monad throws an error with fail. And for some reason
(perhaps outdated tutorials) people generally still use fail intending to
throw an error; anecdotally, we had one job candidate who used fail in the
list monad thinking it would throw an error. Personally, I find `fail
"message" = []` to be very surprising behavior, but no matter.

To be concrete, we had code that ran in an IO stack using fail, and then
someone accidentally factored it such that it ran in the list monad, e.g.

```
x <- maybe (fail ...) return maybeList
-- to
let x = maybe (fail ...) (map foo) maybeList
```

Which the type checker didnt complain about. Now, 2 months later, we had
weird errors and it took a bit of debugging to figure out this was silently
setting x to [] instead of throwing an error. In our codebase, we pretty
much exclusively want error and never want the "semantically equivalent to
mzero" definition, so it makes more sense for us to just blanket ban fail
via hlint instead of a soft "dont use fail unless youre writing FromJSON
instances" policy.

**Comment by bergmark** [comment]
> it makes more sense for us to just blanket ban fail via hlint instead of a soft "dont use fail unless youre writing FromJSON instances" policy.

How about locally re-exporting `parseFail = fail` with a hlint ignore on that definition?

**Comment by phadej** [comment]
> Well for one, the IO monad throws an error with fail.

And?

E.g. in `exceptions` package: 

```haskell
MonadThrow []
MonadThrow Maybe
MonadThrow IO
```

Would you forbid using `throwM` as well? or `Alternativ`'s `empty` (which is `[]`, `Nothing` and `failIO "mzero"`)!

---

That said, there are:

- [`typeMismatch`](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson-Types.html#v:typeMismatch)
- and [`unexpected`](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson-Types.html#v:unexpected)

for slightly more structured errors. Would these fit your use-case better than plain (alias to) `fail`?

**Comment by brandon-leapyear** [comment]
> How about locally re-exporting `parseFail = fail @Parser` with a hlint ignore on that definition?

Yeah, sure, that'd work. Would this be temporary or the official stance?

> Would you forbid using throwM as well? or Alternativ's empty (which is [], Nothing and failIO "mzero")!

Sure, I guess my main points here would be:
* `fail` is in `Prelude`, so it's much more easily reachable and "expected to do the right thing" than `throwM`, where you're explicitly opting into the MonadThrow machinery and you understand how that works
* `empty` doesn't have a string argument, so it doesn't give an impression of it throwing an error with a message like `fail` does

> That said, there are:
> * typeMismatch
> * and unexpected

Those don't seem well suited to show a custom error message; if I didn't care about the custom error message, I'd just do `mzero`. Additionally, they seem to be specifically for indicating type errors, not domain errors (e.g. parsing `Natural` should show a "expected non-negative integer, got: -10" error; using `typeMismatch`, this would be an odd "expected non-negative integer, but encountered Number" error).

**Comment by phadej** [comment]
Wait, https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson-Types.html#v:parseFail isn't that what you ask for?

**Comment by brandon-leapyear** [comment]
ah *facepalm* yes you're right. Thanks

**Comment by bergmark** [comment]
nice to see that we had it alteady, probably since before MonadFail? :) I would still recommend a custom prelude for larger projects, there is so much stuff i want readily available and some things i want to avoid from base
