### ISSUE TITLE
MonadFix instance for Parser

### ISSUE THREAD

**Issue by robrix** [haskell/aeson#927]
I'm parsing JSON into a cyclic graph. Right now I'm producing `IntMap Foo -> Foo` and then taking a fixpoint to make `IntMap Foo`. If I had `MonadFix` available to me, I could eliminate the extra step, which would be very convenient.

It looks like the parser is a simple two continuation implementation, so a `MonadFix` instance taking a fixpoint over all branches shouldn't be too hard to implement. I'd be happy to submit a PR if the change would be welcome.

Thank you!

**Comment by Lysxia** [comment]
If that is possible, perhaps a `MonadFix` instance could also be added to `ContT` in transformers?

**Comment by phadej** [comment]
@Lysxia `Parser` is more like `Codensity`, but there is unsolved issue re it: https://github.com/ekmett/kan-extensions/issues/64 no-one had shown that laws hold for any implementation.

If @robrix has an implementation and (a sketch of) a proof that its lawful, then let's add it. If there isn't, i'd rather ask him to use his `mfix` implementation explicitly. (It's not so neat as `mdo`, but then you don't need a proof!)

**Comment by Lysxia** [comment]
I see. That issue specifically affects `CodensityT` though. `Codensity a` is isomorphic to `a` (and `Parser a` to `JSONPath -> Either (JSONPath, String) a`). That isomorphism can be leveraged by an implementation such as the one in mmtl. It's only not lawful when considering the whole range of monads `CodensityT` may be applied to.

**Comment by robrix** [comment]
Here's the implementation I have, applied to a somewhat abridged variation on `Parser` (for the sake of brevity):

```haskell
newtype P a = P {runP :: forall f r . (String -> f r) -> (a -> f r) -> f r}
```

Note that this type is a close analogue of `Parser`, missing only `JSONPath`. In particular, it retains the quantifiers. Then we have our fixpoint:

```haskell
instance MonadFix P where
  mfix f = P (\ e s -> runP (fix (f . lower)) e s)
    where
    lower :: P a -> a
    lower p = runIdentity (runP p (const (error "mfix (P): empty")) pure)
```

This is based loosely on [the one I wrote for the church-encoded `ErrorC` type in `fused-effects`](https://github.com/fused-effects/fused-effects/blob/36bec2d6c0e97f7e01df97acd15012e1735c28bf/src/Control/Carrier/Error/Church.hs#L85-L91), which is [tested quite thoroughly](https://github.com/fused-effects/fused-effects/blob/36bec2d6c0e97f7e01df97acd15012e1735c28bf/test/Error.hs#L25-L27) against the [`Monad`](https://github.com/fused-effects/fused-effects/blob/36bec2d6c0e97f7e01df97acd15012e1735c28bf/test/Monad.hs#L23-L32) and [`MonadFix`](https://github.com/fused-effects/fused-effects/blob/36bec2d6c0e97f7e01df97acd15012e1735c28bf/test/MonadFix.hs#L23-L30) laws (using stochastically generated programs built up from monad operations and the carrier type's own operations; if you can't tell, I'm rather proud of these tests 😊). Still, validation isn't verification, so I'll try my hand at a (sketch of a) proof. First a couple of notes:

1. Note that the `MonadFix` laws serve to push the fixpoint through binds right to the `return`s. This will come up later.
2. In order to take a fixpoint we need to have some value to pass to the function. We can't produce one in the failure case, so as with the instances for `Maybe` and `Either` we just error out immediately. This is an inevitable consequence of the type and IMO doesn't count against our adherence to the laws.
3. We also have to lower successful values to `a`, but _aha!_ we actually return `f r`, which can't unify. So we have to take the fixpoint of an internal parser and then run _that_ to obtain the values to relay to our continuations. This is also why `Identity` raises its funky head.

And the proof, law-wise:

**Purity:** `return a = P (\ _ s -> s a)`, so we see that `lower` will hit the identity case immediately—success—and we'll push the fixpoint along, exactly as desired.

**Left shrinking:** This law tightens the fixpoint, pulling binds leftwards out of the scope. This one is harder to do by calculation, just because of the noise, so I'll take a different tack. First, failures truncate binds; therefore, we can ignore failures. Successes then map pure values to final results, just like `return` does. I am a little shaky here but I think that means we can take the rest of this by proxy to the purity case?

**Sliding:** Sliding would be an instance of left shrinking if not for strictness. I'll be honest, I've never been certain what this law _means_, so I'm not sure I can do better than validation. Might be one for calculation?

**Nesting:** If we didn't nest like that the rest of the laws wouldn't hold, I think. In particular, the inner `mfix` is in the return position for the outer one, which means it's one big happy family—the operand has to be the same and the computed value has to be the same.

This is a sketch, and quite a sketchy sketch at that, but it's already far more work than I was expecting to invest 😅 Hopefully it will suffice.

**Comment by robrix** [comment]
> If that is possible, perhaps a `MonadFix` instance could also be added to `ContT` in transformers?

I think this is precluded by the rigid instantiation of `r`, alas.

**Comment by Lysxia** [comment]
Its seems those tests only test `ErrorC e Identity` which is isomorphic to the very tame `Either e`. Continuation monad transformers are much whackier on any other monad than `Identity`.

`mfix f` wants to "apply `f` to its result"; the problem is that in the continuation monad, the "result" is whatever the continuation is applied to, but it could be applied zero times, or infinitely many times, so the "result" is a quite ill-defined concept.

But `Parser` is already a version specialized to `Identity`, so that's not a problem here. The `MonadFix` instance is the composition of those for `ReaderT` and `Either` and the laws follow from that.

On a more low-level note, the version of `mfix` for this simplified `P` is also quite different from the one you linked to in `fused-effects`. In particular the parser is re-run every time the input is needed: you are taking the `fix` of a function `P a -> P a`, whereas you need a `fix` of `a -> a` in order to create a single circular thunk of type `a`.
