### ISSUE TITLE
`Day` parser is more lenient than docs suggest

### ISSUE THREAD

**Issue by jlavelle** [haskell/aeson#929]
The docs state that `day` parses years in `YYYY` format:
https://github.com/haskell/aeson/blob/65fca856304c0b323d538cc783493d8d7a145114/attoparsec-iso8601/src/Data/Attoparsec/Time.hs#L44-L48
In reality it can parse any number of digits as a year since it uses `decimal` and does no further checking.

**Comment by Lysxia** [comment]
One reason for mandating 4 digits is that it would catch truncated formats YY-MM-DD, which very likely mean 19YY or 20YY instead of some time in the first century AD as currently interpreted by the parser.

**Comment by Lysxia** [comment]
> Would it be a breaking change to add this restriction?

I'd classify this as a breaking change, to be on the safe side.

**Comment by phadej** [comment]
Yes, unfortunately this is a breaking change.

I'll try to remember if I had something in mind (in addition to #876) which is technically a breaking change, but in practice no-one would notice.

**Comment by phadej** [comment]
Fixed in #930
