### ISSUE TITLE
Add `withEachKV`

### ISSUE THREAD

**Issue by sjshuck** [haskell/aeson#938]
Sometimes an object has an arbitrary set of names, but those names' values all follow the same schema.  Example:
```javascript
{
    "foo": {"num": 1, "pog": true},
    "bar": {"num": 1},
    "baz": {"num": 0, "pog": true}
}
```
Each of these name/value pairs will typically be parsed into some data structure that includes information from both the name and the value.

Add a function like this:
```haskell
withEachKV :: String -> (Key -> Value -> Parser a) -> Value -> Parser [a]
withEachKV label p = withObject label $ mapM parseKV . Data.Aeson.KeyMap.toList where
    parseKV (k, v) = p k v <?> Key k
```
Usage:
```haskell
newtype Things = Things [Thing]

instance FromJSON Things where
    parseJSON = fmap Things . withEachKV "things" parseThing where
        parseThing name = withObject "thing" $ \o -> do
            num <- o .: "num"
            pog <- o .:? "pog" .!= False
            return $ Thing name num pog
```

I don't love what I'm calling it, need more testing to see if error messages are good enough, unsure about monomorphic `[]`, etc. etc., but this is the basic idea.  Let me know what you think.

**Comment by sjshuck** [comment]
Updated to show usage.

I really want something like this, but dang if it isn't fiddly and difficult to use.

- You have to deal with the `[Thing]` in an awkward way, like `(fmap Thing . ) $ ...` if you want to keep writing `parseJSON =` in the idiomatic point-free way.  Not sure there's a better alternative than post-processing helper function like `things $` as shown above.
- You can't use `instance FromJSON Thing` because the name is coming from "outside" the JSON.

**Comment by Colton-Clemmer** [comment]
@sjshuck I've been looking into how this could be implemented, but I think I found an already existing solution that might work for you. Have you tried doing `decode jsonS :: Maybe (KM.KeyMap Thing)` where `jsonS` is a byte string? That will give you a key map for the top level items and if you wanted to turn it into a list you could do `KM.toList`.

**Comment by sjshuck** [comment]
@Colton-Clemmer Thanks for the suggestion.  The problem with `Thing` is that its name would come from the key and its other attributes would come from the value.  So it would be more like
```haskell
decode jsonS :: Maybe (KM.KeyMap ThingMissingItsName)
```
following your example.  Which is not the data model I want.

I think I'm going to close this because it's not terrible to implement without helper functions and the helper function itself is awkward to use.
