### ISSUE TITLE
Expose a `toByteString : Encoding -> ByteString` function

### ISSUE THREAD

**Issue by sebbes-at-decath** [haskell/aeson#940]
I needed a `toByteString : Encoding -> ByteString` function and really struggled to find how to this.

Finally, it turned out this is pretty trivial and I succeeded to write this:
```hs
toByteString : Encoding -> ByteString
toByteString encoding =
  encoding
    & fromEncoding
    & toLazyByteString
````
Searching on Hoogle is not really helpful since:
* `fromEncoding : Encoding' tag -> Builder` doesn't have `Encoding` in its signature,
* when unfamiliar to the `ByteString` and `Builder` type (as I was), it's really difficult to know we have to search for this `Builder` thing when searching on Hoogle.

I had to look into the source code to be able writing this little function, whereas it seems like a common function we could need.

Then, my suggestion is to add this function and document it as well (in the same way the `encode` function is already here).

**Comment by phadej** [comment]
https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson-Encoding.html#v:encodingToLazyByteString ?
