### ISSUE TITLE
Export `KeyMap.mapWithKey`?

### ISSUE THREAD

**Issue by i-am-tom** [haskell/aeson#943]
Hi!

I've noticed that [`mapWithKey` is defined but not exported](https://github.com/haskell/aeson/blob/master/src/Data/Aeson/KeyMap.hs#L194); I _guess_ the reason is that it's only defined for `Map` and not `HashMap`? If this is indeed the reason, I'm not sure how this module would work for `HashMap` given that we export it regardless for [`imap`](https://github.com/haskell/aeson/blob/master/src/Data/Aeson/KeyMap.hs#L654), and I don't think that's in an `#ifdef` block. Is this a bug, or is there something clever going on that I can't spot?

If necessary, I'm happy to PR `mapWithKey` for `HashMap` implemented as a `traverseWithKey` via `Identity`!

Thanks,
Tom

**Comment by phadej** [comment]
It was an oversight to not export that. Thanks for spotting.

**Comment by i-am-tom** [comment]
Thanks for fixing! Do you know when this is likely to be published?

**Comment by phadej** [comment]
Soon, hopefully this week, there is one thing I want to do for the next release.
