### ISSUE TITLE
Can attoparsec-iso8601 be a dependency of aeson?

### ISSUE THREAD

**Issue by Bodigrim** [haskell/aeson#978]
https://github.com/haskell/aeson/blob/66b0b0d323a83fbfd94a4f8bfa1699ef55ce6159/aeson.cabal#L62-L64
https://github.com/haskell/aeson/blob/66b0b0d323a83fbfd94a4f8bfa1699ef55ce6159/aeson.cabal#L80-L94

Why not just add `attoparsec-iso8601` to `build-depends` of `aeson`?

**Comment by phadej** [comment]
`aeson-2.2` will depend on `text-iso8601`, and not duplicate the parsing code for `time` stuff. (Let's see if also encoding stuff in the future).

Done in #1032
