### ISSUE TITLE
Arbitrary instance seems low quality

### ISSUE THREAD

**Issue by ChickenProp** [haskell/aeson#980]
Here are some samples I get from it (aeson-2.0.3.0, but it looks like the instance hasn't changed):

```
ghci> let mySample n = do { vals <- sample' $ resize n (arbitrary @Value); mapM_ (putStrLn . read . show . encode) vals; putStrLn "" }

ghci> mySample 0
""
false
""
true
null
null
""
null
0
0
null

ghci> mySample 1
[]
[]
{}
{}
{}
[]
{}
[]
{}
[]
{}

ghci> mySample 2
[[]]
[[]]
[[]]
[[]]
[[]]
{"":[]}
[[]]
{">X":{}}
[[]]
[{}]
{"ó±¦¤ð":{}}

ghci> mySample 3
{"\u000fW":{},"q":[]}
[[],[]]
[[{}]]
{"\\C":{"2":[]}}
[{},[]]
[[],{}]
[{"":{}}] ±":[]}
[{},{}],"á
[{},{}]
[[[]]]
```

The current implementation is:

```haskell
instance QC.Arbitrary Value where
    arbitrary = QC.sized arbValue

arbValue :: Int -> QC.Gen Value
arbValue n
    | n <= 0 = QC.oneof
        [ pure Null
        , Bool <$> QC.arbitrary
        , String <$> arbText
        , Number <$> arbScientific
        ]

    | otherwise = QC.oneof
        [ Object <$> arbObject n
        , Array <$> arbArray  n
        ]

arbText :: QC.Gen Text
arbText = T.pack <$> QC.arbitrary

arbScientific :: QC.Gen Scientific
arbScientific = Sci.scientific <$> QC.arbitrary <*> QC.arbitrary

arbObject :: Int -> QC.Gen Object
arbObject n = do
    p <- arbPartition (n - 1)
    KM.fromList <$> traverse (\m -> (,) <$> QC.arbitrary <*> arbValue m) p

arbArray :: Int -> QC.Gen Array
arbArray n = do
    p <- arbPartition (n - 1)
    V.fromList <$> traverse arbValue p

arbPartition :: Int -> QC.Gen [Int]
arbPartition k = case compare k 1 of
    LT -> pure []
    EQ -> pure [1]
    GT -> do
        first <- QC.chooseInt (1, k)
        rest <- arbPartition $ k - first
        QC.shuffle (first : rest)
```

And I think there are two problems here. The first is that `arbText` and `arbScientific` are only called when the generator size is 0, so they only produce `""` and `0`. The second is that `arbPartition` never produces a list containing 0, so it never puts `Null`/`Bool`/`String`/`Number` inside an `Object` or `Array`.

I expect that simply allowing the first four constructors to be produced with a positive generator size would be sufficient here, though having `arbPartition` sometimes generate a 0 might also be a mild improvement.

**Comment by phadej** [comment]
Changing

```haskell
arbValue :: Int -> QC.Gen Value
arbValue n
    | n <= 0 = QC.oneof
```

to

```haskell
arbValue :: Int -> QC.Gen Value
arbValue n
    | n <= 1 = QC.oneof
```

should be enough.

> I expect that simply allowing the first four constructors to be produced with a positive generator size 

That will be unoptimal. It will skew distribution towards smaller values. Currently we respect the size (though have a bug you spotted)

**Comment by ChickenProp** [comment]
I think that change would still only give small strings (empty and length-one) and numbers (0, ±1 and ±10).

I agree my suggestion would make things smaller overall. To reduce that effect, perhaps use `frequency` to select `Object` and `Array` more often? (E.g. 1 for the non-recursive constructors and 4 for the recursive ones would mean we only use a non-recursive one 1/3 of the time.)

I don't think "never generate a simple constructor at large sizes" is standard, fwiw. E.g. for both `[]` and `Map`, a sample at size 10 seems to produce at least one empty value (`[]` or `fromList []`) something around half the time.

**Comment by phadej** [comment]
> I think that change would still only give small strings (empty and length-one) and numbers (0, ±1 and ±10).

It won't for larger sizes.

The idea in current implementation is very simple: If size `n` is requested, then there is `n` `Value` constructors in the generated value. The size of strings and numbers is not affected.

> I don't think "never generate a simple constructor at large sizes" is standard, fwiw. 

It's indeed not worth much. Instance for `[]` is in particular "broken". Try to generate `[[[Int]]]` and do anything in reasonable time with it, the generated lists are too big, because the generator doesn't propagate size downwards.

**Comment by ChickenProp** [comment]
> It won't for larger sizes.

Oh yeah, I stand corrected. The initial call to `arbValue` has the parameter set to the generator size, but recursive calls to it won't. The generator size stays fixed while the parameter gets smaller, so the eventual calls to `arbitrary` are at the original size.

> If size `n` is requested, then there is `n` `Value` constructors in the generated value.

I hadn't noticed that. That is kinda neat.
