### ISSUE TITLE
Aeson support for conveniently decoding string types like String, strict and lazy Text

### ISSUE THREAD

**Issue by malteneuss** [haskell/aeson#982]
When combining Aeson with other libraries that don't produce lazy Bytestrings (e.g. decoding from Strings that System.Process uses) i always have to google for quite unconvenient conversion functions like in https://gist.github.com/dino-/28b09c465c756c44b2c91d777408e166. For example, to decode a String we first have to convert it to lazy Bytestring through lazy Text:
```
import Data.Text.Lazy                   as TL
import Data.Text.Lazy.Encoding    as TL

-- String -> BL.Bytestring
fromString = TL.encodeUtf8 . TL.pack
```
Does Aeson support decoding from other string types more conveniently? If not, would it make sense to add them? Either in as code or at least into the documentation? I could create a PR.

**Comment by phadej** [comment]
Don't use `String` with `process`. That is very wrong.

Use e.g. https://hackage.haskell.org/package/process-extras-0.7.4/docs/System-Process-ByteString.html

**Comment by malteneuss** [comment]
Wow, that was quick. Thanks for that suggestion. However, i had several occasions in the past where data i got was either Text or String, so my question in general still stands. I understand that for performance and memory reasons lazy Bytestring is the way to go, but sometimes it's just not convenient.

**Comment by phadej** [comment]
Yes, and the answer is still the same. Most likely there is a way to not produce `String` or `Text` at all.

In theory we could have parsers from `Text` (and `String`) directly, but I'd prefer doing that when is #560 done. That said, I have no idea when I'll have time and motivation at the same time :(

**Comment by malteneuss** [comment]
Alright. Good to know there are already ideas in that direction.
